force-app/main/default/objects/DM_Automated_Payment_Setup__c/DM_Automated_Payment_Setup__c.object-meta.xml
<CustomObject>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Bill__c/DM_Bill__c.object-meta.xml
<CustomObject>
    <label>DM Bill</label>
    <nameField>
        <label>DM Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Charge__c/DM_Charge__c.object-meta.xml
<CustomObject>
    <label>DM Charge</label>
    <nameField>
        <label>DM Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Account__c/DM_Loan_Account__c.object-meta.xml
<CustomObject>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Error__c.field-meta.xml
<CustomField>
    <fullName>DM_Error__c</fullName>
    <label>DM Error</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Invalid_Data__c.field-meta.xml
<CustomField>
    <fullName>DM_Invalid_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
    <label>DM Invalid Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DM_Loan_Disbursal_Transaction__c/DM_Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/DM_Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule__c/DM_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/DM_Repayment_Schedule_Summary__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DM_MigrationJob.cls
Global class DM_MigrationJob implements Database.Batchable<sObject> 
{    
    public String migrationBatchType;
    public static String migrationBatchType;
    public List<DM_Loan_Account__c> errorUpdate = new List<DM_Loan_Account__c>();
    public List<Dm_ValidationWrapper> validationWrapperList = new List<DM_ValidationWrapper>();
    public DM_Metadata_Config_Wrapper configWrapper;
  
    global DM_MigrationJob(){
         //call the class and initialize the wrapper instance here.
         configWrapper = ParserUtil.getParser();         
    }
    global DM_MigrationJob(String batchType){
        configWrapper = ParserUtil.getParser(); 
        migrationBatchType = batchType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        DM_SqlQueryGenerator sqlQuery = new DM_SqlQueryGenerator();        
        return Database.getQueryLocator(sqlQuery.GetQueryString('DM_Repayment_Schedule_Summary__c;DM_Loan_Payment_Transaction__c;DM_Loan_Disbursal_Transaction__c;DM_Charge__c;DM_Bill__c;DM_Automated_Payment_Setup__c;DM_Repayment_Schedule__c;DM_Loan_Account__c',migrationBatchType));
    }//END start

    global void execute(Database.BatchableContext BC, List<DM_Loan_Account__c> dmList) 
    {
        system.debug('scope list '+dmList.size()+ 'list '+dmList);
        Boolean dataCreationFlag = false; 
        
        DM_Validate_Impl handler = new DM_Validate_Impl();
        system.debug('configWrapper '+configWrapper);
        validationWrapperList = handler.validateDMRules(dmList,configWrapper);
        system.debug('validation Wrapper List Result '+validationWrapperList);
        DM_Data_Creation dataCreation;
        For(DM_ValidationWrapper valWrapper : validationWrapperList){
            if(valWrapper.Success){
                system.debug('validation Wrap Success');
                dataCreationFlag = true;
            }else{
                dataCreationFlag = false;
                //failed valWrapper send for updation
                system.debug('DM CL contract '+dmList[0]);
                errorUpdate.add(new DM_Loan_Account__c(Id=dmList[0].Id, DM_Error__c= valWrapper.errorMessage, DM_Invalid_Data__c=True, migration_status__c='Failed'));
                system.debug('Failed');
                break;
            }//END Else
        }//END For 
        
        system.debug('update Failed Record '+errorUpdate);
        if(!errorUpdate.isEmpty())
        	update errorUpdate;
            
        if(dataCreationFlag){
            system.debug('dataCreationFlag - True');
            dataCreation = new DM_Data_Creation();
            dataCreation.DataCreation(dmList);
            system.debug('dataCreation Exit');
        }//END IF(dataCreationFlag)
    }//END execute
    
    global void finish(Database.BatchableContext BC) {
         system.debug('Finish Batch Job');
    }//END finish
}//END DM_MigrationJob