force-app/main/default/objects/DM_Loan_Account__c/DM_Loan_Account__c.object-meta.xml
<CustomObject>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Account__c/fields/Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Type__c</fullName>
    <label>Batch Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DM_SqlQueryGenerator.cls
public with sharing class DM_SqlQueryGenerator 
{
    public String GetQueryString(String srcObject,String migrationBatchType)
    {
        string query ='';
        string parent='';
        string status='pending';
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map <String, Schema.SObjectField> fieldMap = new Map <String, Schema.SObjectField>();
        for(String sObj : srcObject.split(';')){
            fieldMap =schemaMap.get(sObj).getDescribe().fields.getMap();
            String queryFields = Null;
            for(Schema.SObjectField sField :fieldMap.values())
            {
                schema.describefieldresult dfield = sfield.getDescribe();
                if(queryFields != Null)
                {
                    queryFields = queryFields + ',' + dfield.getname();
                }
                else
                {
                    queryFields = dfield.getname();
                }
            } 
            
            if(sobj !='DM_Loan_Account__c'){
                sobj = sobj.replace('__c','s__r');
                query += '(Select '+queryFields+ ' from '+sobj +'),';
            }
            else{
                system.debug('batch Type '+migrationBatchType);
                query= query.removeEnd(',');
                parent = 'select '+queryFields+','+query+' from '+sobj + ' where Migration_status__c = \'' +status+ '\' '; 
                if(migrationBatchType<>null)
                    parent += ' And Batch_Type__c = \''+migrationBatchType+ '\'';
            }           
        }
        System.debug(parent);
        return parent;
    }
}